gmsher = Mesher.Gmsher()
gmsher.setDim(3)
gmsher.appendSolid(1,0)
gmsher.appendSolid(1,1)
gmsher.setElementType("Tet")
gmsher.setElementOrder(1)
gmsher.setMethod(1)
gmsher.setSizeFactor(1)
gmsher.setMinSize(0)
gmsher.setMaxSize(2)
gmsher.cleanGeo()
gmsher.startGenerationThread()
MainWindow.findConplanarPorC("Element",276004,0,1,"coplanar_7")
MainWindow.createGeoComponent("GeoComponent_7","Surface","1;1;1;1","225;224;226;228")
